"""Tests for capture_pins.py and replay_offline's stimulus digest (spec 9.1).

A pin that cannot fail is not a pin, so most cases here must FAIL: a byte
changed, a file missing, a capture-derived trace without a pin, and -- the
reason the pins live in the repo -- a stimulus regenerated together with
its own header hash.

Needs no VTRUX_DATA: it works on small files in a temporary folder.
"""

import hashlib
import os
import shutil
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import capture_pins as CP                                   # noqa: E402
import machine as M                                         # noqa: E402
import replay                                               # noqa: E402

failures = 0


def check(cond, what):
    global failures
    print(("  ok  " if cond else "FAIL  ") + what)
    if not cond:
        failures += 1


def sha(b):
    return hashlib.sha256(b).hexdigest()


def write(folder, name, data):
    with open(os.path.join(folder, name), "wb") as f:
        f.write(data)


def fnv1a64(b):
    h = 0xcbf29ce484222325
    for c in b:
        h = ((h ^ c) * 0x100000001b3) & 0xFFFFFFFFFFFFFFFF
    return "%016X" % h


def l3_file(body):
    """An L3 stimulus file whose header carries its body's hash, the way
    the generator writes it (l3_replay.cpp checks exactly that)."""
    return b"# L3 stimulus\n# fnv1a64 " + fnv1a64(body).encode() + b"\n" + body


def files_cases(root):
    trace = b"C 0 18FFD4C0 1 0100000000000000\nT 0\n"
    l3 = l3_file(b"V 1 420 0 0011223344556677\n")
    saved = (CP.TRACE_PINS, CP.L3_PINS)
    CP.TRACE_PINS = {"cap.trace": sha(trace)}
    CP.L3_PINS = {"l3_stimulus.txt": sha(l3)}
    try:
        write(root, "cap.trace", trace)
        write(root, "syn_a.trace", b"x")
        write(root, "unit_b.trace", b"y")
        write(root, "l3_stimulus.txt", l3)
        p, n = CP.check_traces(root)
        check(not p and n == 1,
              "the pinned trace matches; syn_ and unit_ traces need no pin")
        p, n = CP.check_l3(root)
        check(not p and n == 1, "the pinned L3 file matches")

        write(root, "cap.trace", trace.replace(b"01000000", b"01000001"))
        p, _ = CP.check_traces(root)
        check(len(p) == 1 and "cap.trace" in p[0] and "changed" in p[0],
              "one byte changed in a capture trace FAILS -> %s" % p)
        write(root, "cap.trace", trace)

        os.remove(os.path.join(root, "cap.trace"))
        p, n = CP.check_traces(root)
        check(len(p) == 1 and "missing" in p[0] and n == 0,
              "a pinned trace that is missing FAILS")
        write(root, "cap.trace", trace)

        write(root, "newcapture.trace", trace)
        p, _ = CP.check_traces(root)
        check(len(p) == 1 and "newcapture.trace" in p[0]
              and "neither pinned" in p[0],
              "a trace that is neither pinned nor synthetic FAILS -> %s" % p)
        os.remove(os.path.join(root, "newcapture.trace"))

        # regenerated by a changed parser: new body AND a header hash that
        # agrees with it -- l3_replay.cpp's self-check would pass this
        regen = l3_file(b"V 1 420 0 0011223344556678\n")
        write(root, "l3_stimulus.txt", regen)
        hdr = regen.split(b"\n")[1].split()[-1].decode()
        body = b"\n".join(regen.split(b"\n")[2:])
        check(hdr == fnv1a64(body),
              "(premise) the regenerated file's header hash agrees with its "
              "body, so a self-referential check passes it")
        p, _ = CP.check_l3(root)
        check(len(p) == 1 and "changed" in p[0],
              "the same regenerated file FAILS against the repo-held pin")
        p = CP.check_one(os.path.join(root, "l3_stimulus.txt"))
        check(len(p) == 1, "check_one (host_bridge) fails it too")
        write(root, "l3_stimulus.txt", l3)
        check(not CP.check_one(os.path.join(root, "l3_stimulus.txt")),
              "check_one passes the pinned file")
        write(root, "other_stimulus.txt", l3)
        p = CP.check_one(os.path.join(root, "other_stimulus.txt"))
        check(len(p) == 1 and "no pin" in p[0],
              "check_one FAILS a file whose name has no pin")
    finally:
        CP.TRACE_PINS, CP.L3_PINS = saved


def regress_cases():
    saved = CP.REGRESS_PINS
    raw = {"a.log": "1" * 64}
    CP.REGRESS_PINS = {"c": dict(sources=raw, stimulus="2" * 64,
                                 frames_in=10)}
    try:
        check(not CP.check_regress("c", raw, "2" * 64, 10),
              "regress: raw files, stream and count all match -> passes")
        p = CP.check_regress("c", raw, "3" * 64, 10)
        check(len(p) == 1 and "parser" in p[0],
              "same raw capture, different stream FAILS and names the "
              "parser / pre-filter / bus choice -> %s" % p)
        p = CP.check_regress("c", raw, "2" * 64, 11)
        check(len(p) == 1 and "11 frames" in p[0],
              "same digest, different frame count FAILS")
        p = CP.check_regress("c", {"a.log": "9" * 64}, "3" * 64, 10)
        check(len(p) == 2 and "raw capture" in p[0] and "parser" not in p[1],
              "a changed raw capture FAILS as such, without blaming the "
              "parser -> %s" % p)
        p = CP.check_regress("c", {}, "2" * 64, 10)
        check(p and "raw capture" in p[0], "a missing raw file FAILS")
        p = CP.check_regress("nopin", raw, "2" * 64, 10)
        check(len(p) == 1 and "no pin" in p[0] and "measured" in p[0],
              "a case with no pin FAILS and prints what it measured")
    finally:
        CP.REGRESS_PINS = saved


def digest_of(frames):
    """replay_offline's stimulus digest over `frames`, (t_s, id, ext,
    data), with the parser stubbed out."""
    saved = replay.iter_pt
    replay.iter_pt = lambda path, bus_filter=None, ids=None: iter(frames)
    try:
        core = M.InterposerCore(M.Config(), now_ms=0)
        res = replay.replay_offline("unused", core, bus_filter=0)
    finally:
        replay.iter_pt = saved
    return res["stimulus_sha256"], res["frames_in"]


def digest_cases():
    base = [(0.000, 0x18FFD4C0, True, bytes.fromhex("0100000000000000")),
            (0.012, 0x420, False, bytes.fromhex("0011223344556677")),
            (0.100, 0x18EFC000, True, bytes.fromhex("0000000000000000"))]
    d0, n0 = digest_of(base)
    check(n0 == 3 and len(d0 or "") == 64,
          "replay_offline reports a stimulus digest over its 3 frames")
    check(digest_of(list(base))[0] == d0,
          "the digest is stable for the same stream")
    flip = list(base)
    flip[1] = (0.012, 0x420, False, bytes.fromhex("0011223344556676"))
    check(digest_of(flip)[0] != d0, "one data byte changed moves the digest")
    shift = list(base)
    shift[1] = (0.013, 0x420, False, base[1][3])
    check(digest_of(shift)[0] != d0, "a frame 1 ms later moves the digest")
    ext = list(base)
    ext[1] = (0.012, 0x420, True, base[1][3])
    check(digest_of(ext)[0] != d0, "the extended flag moves the digest")
    check(digest_of(base[:2])[0] != d0, "a dropped frame moves the digest")
    check(digest_of([base[1], base[0], base[2]])[0] != d0,
          "two frames swapped moves the digest")


def main():
    root = tempfile.mkdtemp(prefix="pins_")
    try:
        files_cases(root)
    finally:
        shutil.rmtree(root, ignore_errors=True)
    regress_cases()
    digest_cases()
    if failures:
        print("\n%d failure(s)" % failures)
        return 1
    print("\ncapture_pins_test: all checks OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
